<a href="https://colab.research.google.com/github/Vladik76/goit-ds-hw-03/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b = np.zeros( (3, 3) )
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
c = np.random.randint(1 ,11, size=(5, 5))
c

array([[1, 5, 1, 5, 4],
       [7, 2, 3, 4, 5],
       [3, 3, 9, 9, 7],
       [9, 4, 8, 9, 8],
       [1, 9, 5, 5, 1]])

In [ ]:
d = np.random.random((4, 4))
d

array([[0.57246222, 0.74544407, 0.17308064, 0.04677092],
       [0.66929082, 0.34946567, 0.56367477, 0.54235553],
       [0.76366299, 0.31260992, 0.08014459, 0.48793359],
       [0.67647822, 0.17067328, 0.45719343, 0.06349564]])

In [ ]:
e = np.random.randint(1 ,11, size=(5))
f = np.random.randint(1 ,11, size=(5))
print(e)
print(f)
print("====")
print(e + f)
print(e - f)
print(e * f)



[ 8  5 10  4  7]
[ 7  9  8 10  6]
====
[15 14 18 14 13]
[ 1 -4  2 -6  1]
[56 45 80 40 42]


In [ ]:
e = np.random.randint(1,100,size=(7)) #We can also use np.random.randn()
f = np.random.randint(1,100,size=(7))

print(np.dot(e, f))

27327


In [ ]:
a = np.random.randint(1 ,11, size=(2, 2))
b = np.random.randint(1 ,11, size=(2, 3))
c=np.dot(a, b)

c

array([[ 62, 108,  72],
       [ 44,  56,  48]])

In [ ]:
a = np.random.randint(1 ,11, size=(3, 3))
a_inv = np.linalg.inv(a)
print(a_inv)


[[ -1.75   0.25   0.5 ]
 [ 11.25  -1.75  -2.5 ]
 [-16.25   2.75   3.5 ]]


In [ ]:
a = np.random.random((4, 4))
b = a.T
print(b)

[[0.41895773 0.36436771 0.99661063 0.67633467]
 [0.64799323 0.93798372 0.77312628 0.27809132]
 [0.75019413 0.78995494 0.52300249 0.58865418]
 [0.49236612 0.21184494 0.53410281 0.35247772]]


In [ ]:
a = np.random.randint(1 ,11, size=(3, 4))
b = np.random.randint(1 ,11, size=(4))
print(np.dot(a, b))

[87 34 72]


In [ ]:
a = np.random.random((2, 3))
b = np.random.random((3))

print(np.dot(a,b))

[1.0688742  0.94239692]


In [ ]:
a = np.random.randint(1 ,11, size=(2, 2))
b = np.random.randint(1 ,11, size=(2, 2))

print(a*b)

[[18 54]
 [36 36]]


In [ ]:
a = np.random.randint(1 ,11, size=(2, 2))
b = np.random.randint(1 ,11, size=(2, 2))

print(np.dot(a, b))

[[14 38]
 [14 89]]


In [ ]:
a = np.random.randint(1 ,101, size=(5, 5))
print(a.sum())

1316


In [ ]:
a = np.random.randint(1 ,11, size=(4, 4))
b = np.random.randint(1 ,11, size=(4, 4))

print(a-b)

[[-2  1  8 -1]
 [-2  1  1 -1]
 [ 3 -1 -1  0]
 [-8  4 -4 -3]]


In [ ]:
a = np.random.random((3, 3))
sum_of_rows = np.sum(a, axis = 1)
print(sum_of_rows)

[1.4717288  1.58121539 1.87361068]


In [ ]:
a = np.random.randint(1 ,101, size=(3, 4))
b = np.multiply(a, a)
print(a)
print("===")
print(b)

[[32 43 42 40]
 [ 1  5 78 37]
 [80  7 70 11]]
===
[[1024 1849 1764 1600]
 [   1   25 6084 1369]
 [6400   49 4900  121]]


In [ ]:
a = np.random.randint(1 ,51, size=(1, 4))
b = np.sqrt(a)
print(a)
print(b)

[[28 15 27 25]]
[[5.29150262 3.87298335 5.19615242 5.        ]]
